// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainNamePorts) DeepCopyInto(out *DomainNamePorts) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainNamePorts.
func (in *DomainNamePorts) DeepCopy() *DomainNamePorts {
	if in == nil {
		return nil
	}
	out := new(DomainNamePorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyDNSEgress) DeepCopyInto(out *NetworkPolicyDNSEgress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyDNSEgress.
func (in *NetworkPolicyDNSEgress) DeepCopy() *NetworkPolicyDNSEgress {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyDNSEgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkPolicyDNSEgress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyDNSEgressList) DeepCopyInto(out *NetworkPolicyDNSEgressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkPolicyDNSEgress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyDNSEgressList.
func (in *NetworkPolicyDNSEgressList) DeepCopy() *NetworkPolicyDNSEgressList {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyDNSEgressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkPolicyDNSEgressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyDNSEgressSpec) DeepCopyInto(out *NetworkPolicyDNSEgressSpec) {
	*out = *in
	if in.ResolutionSets != nil {
		in, out := &in.ResolutionSets, &out.ResolutionSets
		*out = make([]ResolutionSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyDNSEgressSpec.
func (in *NetworkPolicyDNSEgressSpec) DeepCopy() *NetworkPolicyDNSEgressSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyDNSEgressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyDNSEgressStatus) DeepCopyInto(out *NetworkPolicyDNSEgressStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PolicyStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyDNSEgressStatus.
func (in *NetworkPolicyDNSEgressStatus) DeepCopy() *NetworkPolicyDNSEgressStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyDNSEgressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatus.
func (in *PolicyStatus) DeepCopy() *PolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolutionSet) DeepCopyInto(out *ResolutionSet) {
	*out = *in
	if in.DomainNamePortsSets != nil {
		in, out := &in.DomainNamePortsSets, &out.DomainNamePortsSets
		*out = make([]DomainNamePorts, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolutionSet.
func (in *ResolutionSet) DeepCopy() *ResolutionSet {
	if in == nil {
		return nil
	}
	out := new(ResolutionSet)
	in.DeepCopyInto(out)
	return out
}
