# permissions to do edit networkpolicydnsegresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkpolicydnsegress-editor-role
rules:
- apiGroups:
  - crd.davidamick.com
  resources:
  - networkpolicydnsegresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.davidamick.com
  resources:
  - networkpolicydnsegresses/status
  verbs:
  - get
  - patch
  - update
